#!/bin/sh

dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
 
picom &
dunst &
xset r rate 300 50 &
xmodmap ~/.config/xmodmap/xmodmaprc
sxhkd &
unclutter --timeout 3 &
# low_battery &
xhost +si:localuser:$USER
# xautolock -time 1 -notify 60 -locker slock &

exec $(dbus-launch --exit-with-session awesome)
