#!/bin/sh

// copied from https://wiki.archlinux.org/title/sxiv

if command -v sxiv >/dev/null 2>&1; then
    if [ -d "${@: -1}" ] || [ -h "${@: -1}" ]; then
	sxiv -t "$@"
    else
	sxiv    "$@"
    fi
elif command -v feh >/dev/null 2>&1; then
    feh "$@"
else
    echo "Please install SXIV or FEH!"
fi
