#!/usr/bin/bash

# Get the id number of the touchpad.
# my touchpad is called GlidePoint
tp_id="$(xinput list | grep -i GlidePoint | awk '{ print $6 }' | sed 's/id=//')"


# Find out whether the touchpad is enabled or not.
tp_enabled="$(xinput list-props $tp_id | grep Device\ Enabled | awk '{ print $4 }')"


if [ $tp_enabled = 0 ]
then
  # The touchpad is currently disabled, so turn it on.
  xinput set-prop $tp_id "Device Enabled" 1
  notify-send "Touchpad now on."
  exit 1
fi

if [ $tp_enabled = 1 ]
then
  # The touchpad is currently enabled, so turn it off.
  xinput set-prop $tp_id "Device Enabled" 0
  notify-send "Touchpad now off."
  exit 1
fi

notify-send "tp_toggle: Could not get touchpad status from xinput."
exit 1
